[[endpoints.GET]]
path = "/health"
status = 200
body = "API is up and running"

[[endpoints.GET]]
path = "/users"
status = 200
body = '''
[
  {
    "id": "{{rand}}",
    "name": "{{arg.name}}",
    "email": "",
    "path": "{{path}}"
  }
]
'''

[[endpoints.GET]]
path = "/users/{{name}}"
status = 200
body = '''
{
  "id": 1,
  "name": "{{name}}",
  "email": ""
}
'''

[[endpoints.GET]]
path = "/users/{{name}}/{{id}}"
status = 200
body = '''
{
  "id": "{{id}}",
  "name": "{{name}}",
  "email": ""
}
'''

[[endpoints.POST]]
path = "/users"
status = 201
body = '''
{
  "id": "{{rand}}",
  "name": "Jane Doe",
  "email": ""
}
'''


[[db]]
path = "/db/users/"
data = '''
{
    "users":
        [
            {
                "id": 0,
                "name": "Alberto",
                "surname": "Ruiz",
                "age": 25,
                "admin": true
            },
            {
                "id": 1,
                "name": "Eithne",
                "surname": "Flor",
                "age": 21,
                "admin": false
            },
            {
                "id": 2,
                "name": "Juan",
                "surname": "Perez",
                "age": 52,
                "admin": false
            }
      ]
}
'''
